apiVersion: v1
kind: Service
metadata:
  name: backend-service 
spec:
  type: NodePort
  selector:
    app: dummy-backend
  ports:
  - protocol: TCP
    port: 80 # port on which NodePort will listen
    targetPort: 80 # port on which the container is listening
    nodePort: 30007 # the port on your machine