apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-backend-deployment 
spec:
  replicas: 3
  selector:
  # This is how the ReplicSets/Deployment finds the pods that it owns
  # It must exactly match the labels in the template below.
    matchLabels:
      app: dummy-backend
  template:
    metadata:
      labels:
        app: dummy-backend
    spec:
      containers:
      - name: backend-container
        image: nginx:1.25
        ports:
        - containerPort: 80
